# Generated by Django 2.2.6 on 2019-10-31 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_situation', '0002_auto_20191028_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cuase',
            new_name='cause',
        ),
    ]
