# Generated by Django 2.2.6 on 2019-11-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_situation', '0004_auto_20191031_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manage_center',
            name='point',
        ),
        migrations.RemoveField(
            model_name='manage_center',
            name='time',
        ),
    ]
