# Generated by Django 2.2.7 on 2019-12-17 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manage_center',
            name='cause',
        ),
    ]
