# Generated by Django 2.2.7 on 2019-12-17 03:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0002_remove_manage_center_cause'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_id',
            new_name='Student',
        ),
    ]
